### ISSUE TITLE
su: must be suid to work properly

### ISSUE THREAD

**Issue by rescenic** [zkedem/wsl-tcl-setup#2]
TinyCore v12
![suerror](https://i.ibb.co/rvHVcVh/25-02-2021-1127-23-29-36.png)
I can't install anything without root.

Thank you for your attention.

**Comment by zkedem** [comment]
I'll review that as soon as I can.

**Comment by pcause** [comment]
I had to change the owners of /etc/sudoers to root:root and permissions to 0440 I also had to change owner/permissions on sudo.  Needs to have set sudo permissions to 111 and then chmod a+s on it as well.  that seemed to work

**Comment by rescenic** [comment]
@pcause Thanks I'll try that.
